### ISSUE TITLE
[Bug] 0.8.6 - Calcul des points par équipe 

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#101]
Le calcul des points par équipe n'est pas correctement calculé après les résultats de la première ronde.
(Pj dans le mail du 28/06/2016)
En effet, celon notre configuration (équipe de 5 joueurs , victoire individuel à 1 000 Pts et victoire d'équipe à 5 000Pts), il est impossible d'avoir plus de 10 000Pts par ronde hors nous avons eu plusieurs équipe à plus de 40 K points en ronde 3 par exemple.

Cependant, le classement était correcte.

**Comment by Bojo38** [comment]
Par défaut, il y a un bug qui rajoute la valeur d'un nul à chaque ronde supplémentaire. J'ai commencé à voir les corrections là dessus pour les victoires d'équipes, il faut que je reboucle tous les cas. Cela ne fausse aucunement le classement, car un nul est ajouté pour tout le monde (1 nul ronde 2, 2 nuls ronde 3, 4 nuls ronde 5, etc .....)

**Comment by Bojo38** [comment]
Il s'agit d'un cas hyper spécifique qui ajoute des bonus de match nuls à tout le monde. Problème corrigé sur la branche de developpement.
