### ISSUE TITLE
[Evolution] - La saisie d'une nouvelle valeur écrase l'ancienne au lieu de se concaténer 

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#102]
Serai-t-il possible qu'écrire une valeur écrase l'ancienne valeur plutôt qu'elle vienne se concaténer?

Par exemple, suite à une erreur de saisie dans les sorties (3 au lieu de 1 par exemple), j'ai d'abord écrit 3, puis après vérification, j'ai écris 1 au lieu de supprimer la valeur.

Conséquence, le joueur a eu 31 sorties pour ce match (ça a fait le bonheur de Kadu-c :D )

Merci

**Comment by Bojo38** [comment]
il faut jouer sur la captation de l’événement appui sur touche. Aujourd'hui on rentre dans le mode édition, mais en l’occurrence, avant de rentrer dans le mode édition, il faut supprimer la valeur.

**Comment by Bojo38** [comment]
Corrigé dans la prochaine version
