### ISSUE TITLE
[Evolution] - Double clique depuis la page des résultats permet l'édition du joueur

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#103]
Hello,

Vu qu'on était vachement trop bien organisée à la Lutèce, environ les 2/3 n'avaient pas leur race renseignée au démarrage (environ 100 Joueurs).

Conclusion, j'ai demandé à la fin de la 1ère ronde leur race.
Un double clique sur le joueur dans la page des scores, à permis d'éditer la race, mais ce n'était pas conserver pour les rondes suivantes.

Serai-t-il possible d'ajouter un bouton pour rendre cette modification permanente ?

**Comment by Bojo38** [comment]
Le double-clic depuis la page de résultat permet de changer le roster du joueur pour la ronde. Pour changer un joueur il faut aller dans les paramètres.

**Comment by Bojo38** [comment]
Un click droit sur le coach permet de :
- Editer le coach
- Changer le roster pour la ronde
- changer l'appariement individuel
