### ISSUE TITLE
[Evolution] - Impression des appariements - ajout de l'entête pour chaque match

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#104]
Serai-t-il possible lorsqu'on veut imprimer les appariements d'ajouter l'entête au dessus de chaque matchs (TD, sortie passe agro etc ...) ainsi que le code Pin associé à chaque joueur.?

**Comment by Bojo38** [comment]
Le code PIN n'est utile que pour la saisie par le web. Il est censé être secret, donc pas forcément à afficher.

ajouter l'affichage des critères ne devrait pas poser de problème.

**Comment by Bojo38** [comment]
Est-ce que la fonction recherchée ne serait pas plutôt de créer une fonction d'impression des petites étiquettes que l'on retrouve maintenant dans la plupart des tournois ?

**Comment by Bojo38** [comment]
Les étiquettes sont codées. Un reprise du template HTML sera sans doute à prévoir pour être plus esthétique, mais déjà, cela fonctionne.
