### ISSUE TITLE
[Evolution] - Appariement par équipe - Pouvoir modifier l'appariement à l'intérieur d'une équipe

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#105]
Pour le lutèce en équipe, 
Nous avons eu des malins qui se sont amusés à changer d'adversaire.
Je n'ai pas réussi à modifier de manière simple l'appariement à l'intérieure d'une équipe.
Il faut pour changer l'appariement de l'équipe puis le refaire dans l'autre sens pour pouvoir modifier l'appariement dans l'équipe.

Dans le menu d'appariement, par équipe, ajouter un bouton pour modifier l'appariement par joueur, voir directement un un menu pour l'appariement individuel.

**Comment by Bojo38** [comment]
Cela existe déjà pour l'individuel, cela ne devrait pas être trop difficile de la faire pour l'individuel dans l'équipe.
