### ISSUE TITLE
[Evolution Wiki] - Tourma Mode Serveur - Pré-requis

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#106]
J'ai vu qu'il était possible d'utiliser Tourma en serveur d'affichage et de saisie, par contre il n'est pas écrit dans le wiki les pré-requis logiciel (un tomcat par exemple?) et matériel (clé qui diffuse le wifi?)

**Comment by Bojo38** [comment]
Il n'y a pas de pré-requis (le serveur est dans le logiciel), si ce n'est un réseau. Si on est sur un réseau WiFi commun, sinon, un logiciel qui transforme le PC en point d'accès.
