### ISSUE TITLE
Score remis à zéro automatiquement

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#128]
Salut

Sur la version de tourma de la branche de la correction #125, après la saisie d'un résultat (TD, sortie, passe etc ...), si on se déplace avec les flèches du clavier ou tabulation, le résultat de la case quittée est remis à 0.

Le problème n'est pas reproduis si on se déplace avec la souris;

**Comment by Bojo38** [comment]
Je ne reproduit pas le souci avec la 0.8.7. Dois-je fermer le problème ?

**Comment by Bojo38** [comment]
Je ferme le point.
