### ISSUE TITLE
Team results summary page has summation errors

### ISSUE THREAD

**Issue by hardingnj** [Bojo38/tourma#144]
![image](https://user-images.githubusercontent.com/4437708/41603459-e4d2bdda-73d4-11e8-9b80-1ec186eff60c.png)

Total touchdowns (plus and minus) of all players are one short for all coaches. "Sorties" seems to add up ok.

ie for mubo 4 + 2 + 3 + 2 + 3 != 13

**Comment by Bojo38** [comment]
Thx for submitting, I will try to grab the Lutèce XML file to understand where is the issue

**Comment by Bojo38** [comment]
The correction will be available in the next release

**Comment by Bojo38** [comment]
Corrected un 0.8.10b
