### ISSUE TITLE
Evol : rapport d'équipe 

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#146]
Est-il possible d'ajouter le classement individuel au rapport?

Est-il possible d'envoyer d'un seul clique tous les rapports d'équipe? Actuellement, il faut sélectionner chaque équipe puis imprimer le rapport.

Merci

**Comment by Bojo38** [comment]
j'ai mis un printAll et un export PDF All. Qu'entends tu par ajouter le rapport individuel au rapport ?

Le rapport individuel des coachs à la suite du rapport de l'équipe ?

**Comment by Bojo38** [comment]
option ajoutée.
