### ISSUE TITLE
Menu plein écran -> défilement

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#147]
Est-il possible d'ajouter une pause d'environ 1 seconde entre chaque équipe/tous les x joueurs/équipes ?

Le but est de ralentir artificiellement le defilement.

**Comment by Bojo38** [comment]
je vais essayer de faire varier la vitesse avec les touches + et -, car le défilement dépend de la résolution. Est-ce que cela serait acceptable ?

**Comment by Funny-Valentine** [comment]
Oui je pense
