### ISSUE TITLE
Privacy problems

### ISSUE THREAD

**Issue by Ispurio** [Bojo38/tourma#188]
Hi all, 

I was curious on how you manage the existing players on the NAF site I mean: checking if the NAF number is correct and such, and I discovered that there are several xml lists with the NAF coaches and their NAF number on the repo.  I don't really know if this has to comply with some request or permission from the NAF but as Blood Bowl player I'm a bit concerned. 

Also, on the (master) repo base, you can find the results of the Melting_bowl tournament on an xml file ready to be sent to the NAF. I'm pretty sure that doesn't belong here. 

These are of course minor problems.

**Comment by Bojo38** [comment]
Hello, the NAF Id/nick and results are public and don't include real names, so they can not be legally considered as personnal data. If the real names would have been included, It could have been considered as personnal data, but it not the case. The XML files have been created to simplify the naf nick/id resolution.
