### ISSUE TITLE
[0.8.2a] Pas de statistique affiché

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#70]
Les statistiques ne sont pas affichés.
Le fichier du tournoi est envoyé par mail

**Comment by Bojo38** [comment]
Il y a plusieurs problèmes:
- Problème de rafraîchissement d'un panneau inexistant dans cette configuration
- Problèmes dans le fichier sauvegardé. Il y a des "Nains du chaos" et des "Nains du Chaos", des "Morts-vivants" et des "Morts-Vivants" ainsi que des "Elfes" et des "Elfes Pro"
