### ISSUE TITLE
[0.8.2a] Evo : comptage point équipe

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#72]
Bonjour,

Serai-t-il possible de faire en sorte que les points totaux d'une équipe = point victoire + somme individuelle des joueurs?

**Comment by Bojo38** [comment]
C'est déjà un peu le principe du bonus de victoire et du bonus de nul.

**Comment by Funny-Valentine** [comment]
En effet,je n'avais pas vu l'option, désolé
