### ISSUE TITLE
[0.8.2c] Tournoi par équipe - pb point adversaire

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#78]
Bonjour,
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode, sharing)

Windows7 64bit, sp1
Intel core i5 pro, 8Go ram

Description du problème : 
Après la saisie de la 1ère ronde, les points adversaires par équipes et individuels ne sont pas effectués. Ils restent à 2000 en équipe et 0 en individuel.
Lorsque j'ai passé la ronde suivante, seul les points adversaire en début de ronde est calculé, mais il n'est pas mis à jour.

Pas de log dans l'invite DOS.

Fichier J0_Lutece_10teams_mjoué.xml envoyé par mail (d'une, on n'a pas le droit de déposer des xml, 2, si je transforme en fichier txt, il y a un bug lors du dépot :/)

**Comment by Bojo38** [comment]
Je suis déjà sur le pb de Tristelune à la création d'équipes en 0.7.5. Dès que j'ai résolu je m'attaque à ça.

**Comment by Funny-Valentine** [comment]
Pas de souci,
Sinon ça ressemble au problème réglé dans l'issue #54 non ?

**Comment by Bojo38** [comment]
Un peu, du coup, je vais d'abord reproduire, on verra après. 


     Le Mardi 6 octobre 2015 12h16, Funny-Valentine <notifications@github.com> a écrit :
   

 Pas de souci,
Sinon ça ressemble au problème réglé dans l'issue #54 non ?—

**Comment by Bojo38** [comment]
[J0_Lutece_10teams_mjoué.xml.txt](https://github.com/Bojo38/tourma/files/9076/J0_Lutece_10teams_mjoue.xml.txt)

**Comment by Bojo38** [comment]
Par défaut, les points adversaires calculés sont les "points adversaires sauf match propre" afin que les joueurs n'aient pas intérêt que leurs adversaires marquent des points sur le match en cours.

Si on rétabli les "points adversaires" au lieu des "points adversaires sauf match propre", pas de souci.
