### ISSUE TITLE
[0.8.5] - TourMa plante au démarage avec JAVA7

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#99]
Salut,
Exécuté sur un environnement WIN 7 SP1
4go RAM CPU Intel C5 2,3gh
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

Lorsque je lance Tourma, une stack trace appariait.

Commande pour exécuter Torma :
call "C:\Program Files (x86)\Java\jre7\bin\java.exe" -jar TourMa.0.8.5.jar

Stack trace : 
Exception in thread "main" java.lang.UnsupportedClassVersionError: tourma/MainFrame : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)

Il semblerait de ce que j'ai compris, Tourma a été compilé avec Java 8.
Vu que j'utilise l'ordi du boulot et que je suis sur un projet Tout en Java 7, serai-t-il possible de le recompiler en JAVA 7 (si c'est bien ça l'erreur).
Merci

**Comment by Bojo38** [comment]
Salut,
en effet il y a peut être unne rupture de compatibilité .  Je vais essayer de compiler en Java 7 pour voir. Je te tiens au jus quand c'est fait.
@+
nvoyé depuis Yahoo Mail pour Android
 
 
  Le Dim j Mai PM à 16:32, Funny-Valentine<notifications@github.com> a écrit :   
Salut,
Exécuté sur un environnement WIN 7 SP1
4go RAM CPU Intel C5 2,3gh
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

Lorsque je lance Tourma, une stack trace appariait.

Commande pour exécuter Torma :
call "C:\Program Files (x86)\Java\jre7\bin\java.exe" -jar TourMa.0.8.5.jar

Stack trace : 
Exception in thread "main" java.lang.UnsupportedClassVersionError: tourma/MainFrame : Unsupported major.minor version 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(Unknown Source)
 at java.security.SecureClassLoader.defineClass(Unknown Source)
 at java.net.URLClassLoader.defineClass(Unknown Source)
 at java.net.URLClassLoader.access$100(Unknown Source)
 at java.net.URLClassLoader$1.run(Unknown Source)

Il semblerait de ce que j'ai compris, Tourma a été compilé avec Java 8.
Vu que j'utilise l'ordi du boulot et que je suis sur un projet Tout en Java 7, serai-t-il possible de le recompiler en JAVA 7 (si c'est bien ça l'erreur).
Merci

**Comment by Funny-Valentine** [comment]
Le jar envoyé par mail fonctionne.
Merci

**Comment by Bojo38** [comment]
Il va falloir que je te renvoie un nouveau jar. Il y a eu des corrections pour les tournois par équipes.
Le 13 juin 2016 1:29 PM, Funny-Valentine <notifications@github.com> a écrit :Le jar envoyé par mail fonctionne.
Merci

**Comment by Funny-Valentine** [comment]
la version 0.8.6 n'est pas bonne ?elle est compatible java 7


      De : Bojo <notifications@github.com>
 À : Bojo38/tourma <tourma@noreply.github.com> 
Cc : Funny-Valentine <mailgoog-funny@yahoo.fr>; State change <state_change@noreply.github.com>
 Envoyé le : Lundi 13 juin 2016 22h44
 Objet : Re: [Bojo38/tourma] [0.8.5] - TourMa plante au démarage avec JAVA7 (#99)
   
Il va falloir que je te renvoie un nouveau jar. Il y a eu des corrections pour les tournois par équipes.
Le 13 juin 2016 1:29 PM, Funny-Valentine <notifications@github.com> a écrit :Le jar envoyé par mail fonctionne.
Merci

**Comment by Bojo38** [comment]
Pour être honnête je n'ai pas vérifié l'environnement à la compilation.
Le 13 juin 2016 10:57 PM, Funny-Valentine <notifications@github.com> a écrit :la version 0.8.6 n'est pas bonne ?elle est compatible java 7


      De : Bojo <notifications@github.com>
 À : Bojo38/tourma <tourma@noreply.github.com> 
Cc : Funny-Valentine <mailgoog-funny@yahoo.fr>; State change <state_change@noreply.github.com>
 Envoyé le : Lundi 13 juin 2016 22h44
 Objet : Re: [Bojo38/tourma] [0.8.5] - TourMa plante au démarage avec JAVA7 (#99)
   
Il va falloir que je te renvoie un nouveau jar. Il y a eu des corrections pour les tournois par équipes.
Le 13 juin 2016 1:29 PM, Funny-Valentine <notifications@github.com> a écrit :Le jar envoyé par mail fonctionne.
Merci
